/** @module */
import {
  icon,
  seo,
  title,
  subtitleAnode,
  subscription,
  subtitleCathode,
  subtitleBatteryCell,
  colorsAnode,
  unitAnode,
  colorsCathode,
  unitCathode,
  colorsBatteryCell,
  unitBatteryCell,
  defaultTab,
  commonTabs,
  circleClassColorsAnode,
  checkClassColorsAnode,
  circleClassColorsCathode,
  checkClassColorsCathode,
  circleClassColorsBatteryCell,
  checkClassColorsBatteryCell,
} from './common'

/** @constants */
import { ANODE, CATHODE } from '~/constants/services/constants'

export const SODIUM_ION_BATTERIES_CAPACITIES_AUTHORIZED = {
  defaultTab,
  commonTabs,
  subscription,
  [ANODE.slug]: {
    seo,
    icon,
    title,
    subtitle: subtitleAnode,
    colors: colorsAnode,
    circleClassColors: circleClassColorsAnode,
    checkClassColors: checkClassColorsAnode,
    unit: unitAnode,
    subscription,
    product: subtitleAnode,
    slug: 'sodium-anode',
  },
  [CATHODE.slug]: {
    seo,
    icon,
    title,
    subtitle: subtitleCathode,
    colors: colorsCathode,
    circleClassColors: circleClassColorsCathode,
    checkClassColors: checkClassColorsCathode,
    unit: unitCathode,
    subscription,
    product: subtitleCathode,
    slug: 'sodium-cathode',
  },
  'battery-cell': {
    seo,
    icon,
    title,
    subtitle: subtitleBatteryCell,
    colors: colorsBatteryCell,
    circleClassColors: circleClassColorsBatteryCell,
    checkClassColors: checkClassColorsBatteryCell,
    unit: unitBatteryCell,
    subscription,
    product: subtitleBatteryCell,
    slug: 'sodium-gigafactory',
  },
}
